services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin -d mydb
      interval: 3s
      timeout: 3s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/mydb?schema=public
      - WEB_ORIGIN=http://web
    ports:
      - "3000:3000"
    command: bash -c "npx prisma migrate deploy && npm start"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://server:3000
    ports:
      - "80:80"

  e2e:
    build:
      context: ./
      dockerfile: ./e2e/Dockerfile
    environment:
      - CI=${CI}
      - DATABASE_URL=postgresql://admin:password@db:5432/mydb?schema=public
      - PLAYWRIGHT_BASE_URL=http://web
      - PLAYWRIGHT_API_URL=http://server:3000
    volumes:
      - ./e2e/test-results:/app/test-results
    ports:
      - "9323:9323"
    depends_on:
      - web
