services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin -d mydb
      interval: 3s
      timeout: 3s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/mydb?schema=public
      - WEB_ORIGIN=http://localhost:5173
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma db push && npx prisma db seed && npm run dev"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    command: >
      sh -c "npm run dev"

# 開発時は5173ポートを転送し、ブラウザを通してローカル環境からserverにリクエストされる
# その場合はDocker Network内の通信ではなくなるのでlocalhostをホストに指定する