services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin -d mydb
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - mynetwork

  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/mydb?schema=public
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  test:
    build:
      context: ./
      dockerfile: Dockerfile.test
      args:
        - VITE_BASE_URL=${VITE_BASE_URL:-http://server:3000}
    environment:
      - CI=${CI}
    volumes:
      - ./web/playwright-report:/app/playwright-report
      - ./web/test-results:/app/test-results
      - ./web/tests:/app/tests
      - ./web/playwright.config.ts:/app/playwright.config.ts
      - ./web/playwright.config.vrt.ts:/app/playwright.config.vrt.ts
    ports:
      - "9323:9323"
    tty: true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
