FROM mcr.microsoft.com/playwright:v1.45.1-jammy

ARG VITE_BASE_URL

ENV VITE_BASE_URL=$VITE_BASE_URL

COPY ./web /app

WORKDIR /app

RUN npm install
RUN npm run build 

CMD [ "bash", "-c", "/bin/bash" ]